<a href="https://colab.research.google.com/github/adas754/numpy_interview/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
df=np.genfromtxt('/content/tipsf.csv',delimiter=',',skip_header=1)
df



array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

#what is total bill value

In [6]:
np.sum(df[:,1])

4827.77

In [7]:
import pandas as pd
df1=pd.read_csv('/content/tipsf.csv')
df1.head()

Unnamed: 0  total_bill   tip  sex  smoker  day  time  size
0           0       16.99  1.01    0       0    1     0     2
1           1       10.34  1.66    1       0    1     0     3
2           2       21.01  3.50    1       0    1     0     3
3           3       23.68  3.31    1       0    1     0     2
4           4       24.59  3.61    0       0    1     0     4

In [8]:
df1['total_bill'].sum()

4827.77

#how many smoker are there

In [10]:
np.sum(df[:,4])

93.0

#count how many sat,sun,thursday,friday

In [12]:
np.unique(df[:,5],return_counts=True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19]))

In [14]:
np.bincount(df[:,5].astype(int))

array([87, 76, 62, 19])