<a href="https://colab.research.google.com/github/adas754/numpy_interview/blob/main/NumPy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

- What is Numpy array
- Difference between List and Array
- Properties of Array

In [66]:
import numpy as np

In [67]:
l=[1,2,3,4]

In [68]:
l1=[1,"a",3.0,True]  #hetrogenous

In [72]:
a=np.array([1,2,3,4,'m',1.5])

In [73]:
a.dtype

dtype('<U32')

In [74]:
import numpy as np

# creating and initializing an array
arr = np.array([1, 2, 3, 23, 56, 100,89.7])

# printing the array and checking datatype
print('Array:', arr)

print('Datatype:', arr.dtype)

Array: [  1.    2.    3.   23.   56.  100.   89.7]
Datatype: float64


In [75]:
np.array([1,"a",3.0,True]) #homogeous

array(['1', 'a', '3.0', 'True'], dtype='<U32')

In [76]:
#List vs Array

In [77]:
L=range(10000)#list

In [78]:
%timeit [i**2 for i in L]

3.06 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [79]:
arr=np.array(L)#numpy

In [80]:
%timeit arr**2

8.65 µs ± 2.05 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Properties
- Efficient Data Storage
- High Performance
- Vectorization
- Broad Range of Mathematical Functions
- Broadcasting
- Random Number Generation

#broadcasting

In [81]:
import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print ('First array:' )
print (a)
print ('\n')

print ('Second array:')
print (b)
print ('\n')

print ('First Array + Second Array')
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [82]:
#vectorization

In [83]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5 ])
number = 10

#  number sums up with each array element
result = array1 + number

print(result)

[11 12 13 14 15]


In [84]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.random.randint(1,10)

7

1. **Basic Mathematical Operations**:
   - `np.add()`: Element-wise addition of two arrays.
   - `np.subtract()`: Element-wise subtraction of two arrays.
   - `np.multiply()`: Element-wise multiplication of two arrays.
   - `np.divide()`: Element-wise division of two arrays.
   - `np.exp()`: Compute the exponentials of elements in an array.
   - `np.log()`: Natural logarithm (base e) of elements in an array.
   - `np.sqrt()`: Square root of elements in an array.
   - `np.power()`: Raise elements to a specified power.

2. **Trigonometric Functions**:
   - `np.sin()`, `np.cos()`, `np.tan()`: Sine, cosine, and tangent functions.
   - `np.arcsin()`, `np.arccos()`, `np.arctan()`: Inverse trigonometric functions.
   
3. **Linear Algebra**:
   - `np.dot()`: Dot product of two arrays (vectors or matrices).
   - `np.matmul()`: Matrix multiplication.
   - `np.linalg.inv()`: Inverse of a square matrix.
   - `np.linalg.det()`: Determinant of a square matrix.
   - `np.linalg.eig()`: Eigenvalues and eigenvectors of a matrix.
   - `np.linalg.svd()`: Singular value decomposition of a matrix.

4. **Statistics and Random Numbers**:
   - `np.mean()`: Compute the mean (average) of elements in an array.
   - `np.median()`: Calculate the median of elements in an array.
   - `np.std()`: Compute the standard deviation of elements in an array.
   - `np.var()`: Calculate the variance of elements in an array.
   - `np.random.rand()`: Generate random numbers from a uniform distribution.
   - `np.random.randn()`: Generate random numbers from a standard normal distribution.
   - `np.random.randint()`: Generate random integers within a specified range.

5. **Interpolation**:
   - `np.interp()`: Perform linear interpolation between data points.
   - `np.polyfit()`: Fit a polynomial to a set of data points.
   - `np.polyval()`: Evaluate a polynomial at specified values.

6. **Numerical Integration and Differentiation**:
   - `np.trapz()`: Compute the integral of a function using the trapezoidal rule.
   - `np.gradient()`: Compute the gradient (derivative) of an array.

7. **Signal Processing**:
   - `np.convolve()`: Perform 1D convolution of two arrays.
   - `np.fft.fft()`: Compute the one-dimensional discrete Fourier Transform (DFT).

8. **Miscellaneous**:
   - `np.argmax()`, `np.argmin()`: Find the indices of maximum and minimum values in an array.
   - `np.unique()`: Find unique elements in an array.

In [9]:
#Write a function to Calculate the total sales amount for each product in a Numpy array arr.
#Input: arr = np.array([[100, 200, 150], [300, 400, 250]])

#Output: [400 600 400]

In [10]:
import numpy as np
def cal_sales(arr):
  return np.sum(arr,axis=0)#row wise

In [8]:
arr = np.array([[100, 200, 150], [300, 400, 250]])
cal_sales(arr)

array([400, 600, 400])

In [11]:
#Create a function to find the indices of elements that are greater than a specified threshold in a Numpy array arr.
#Input: arr = np.array([3, 8, 2, 6, 10])

    #- threshold_value= 5

In [65]:
def ind(arr,threeshold):
  return np.where(arr>5)[0] #where function
arr=np.array([3, 8, 2, 6, 10])
print(ind(arr,5))


[1 3 4]


In [27]:
#Write a Function that Remove duplicate elements from a Numpy array arr while preserving order and give you indices.
#Input: arr = np.array([1, 2, 3, 2,  4,1])

#Output: [0 1 2 4]

In [59]:
def rem_dup(arr):
  return np.unique(arr,return_index=True)[1]

In [60]:
arr = np.array([1, 2, 3, 2, 4, 1])

In [61]:
rem_dup(arr)

array([0, 1, 2, 4])